const keys = {
  'Backquote': {code: 'Backquote', key: '`', keyEnShift: '~', keyRu: 'ё'},
  'Digit1': {code: 'Digit1', key: '1', keyEnShift: '!', keyRuShift: '!'},
  'Digit2': {code: 'Digit2', key: '2', keyEnShift: '@', keyRuShift: '"'},
  'Digit3': {code: 'Digit3', key: '3', keyEnShift: '#', keyRuShift: '№'},
  'Digit4': {code: 'Digit4', key: '4', keyEnShift: '$', keyRuShift: ';'},
  'Digit5': {code: 'Digit5', key: '5', keyEnShift: '%', keyRuShift: '%'},
  'Digit6': {code: 'Digit6', key: '6', keyEnShift: '^', keyRuShift: ':'},
  'Digit7': {code: 'Digit7', key: '7', keyEnShift: '&', keyRuShift: '?'},
  'Digit8': {code: 'Digit8', key: '8', keyEnShift: '*', keyRuShift: '*'},
  'Digit9': {code: 'Digit9', key: '9', keyEnShift: '(', keyRuShift: '('},
  'Digit0': {code: 'Digit0', key: '0', keyEnShift: ')', keyRuShift: ')'},
  'Minus': {code: 'Minus', key: '-', keyEnShift: '_', keyRuShift: '_'},
  'Equal': {code: 'Equal', key: '=', keyEnShift: '+', keyRuShift: '+'},
  'Backspace': {code: 'Backspace', key: 'Backspace'},
  'Tab': {code: 'Tab', key: 'Tab'},
  'KeyQ': {code: 'KeyQ', key: 'q', keyRu: 'й'},
  'KeyW': {code: 'KeyW', key: 'w', keyRu: 'ц'},
  'KeyE': {code: 'KeyE', key: 'e', keyRu: 'у'},
  'KeyR': {code: 'KeyR', key: 'r', keyRu: 'к'},
  'KeyT': {code: 'KeyT', key: 't', keyRu: 'е'},
  'KeyY': {code: 'KeyY', key: 'y', keyRu: 'н'},
  'KeyU': {code: 'KeyU', key: 'u', keyRu: 'г'},
  'KeyI': {code: 'KeyI', key: 'i', keyRu: 'ш'},
  'KeyO': {code: 'KeyO', key: 'o', keyRu: 'щ'},
  'KeyP': {code: 'KeyP', key: 'p', keyRu: 'з'},
  'BracketLeft': {code: 'BracketLeft', key: '[', keyEnShift: '{', keyRu: 'х'},
  'BracketRight': {code: 'BracketRight', key: ']', keyEnShift: '}', keyRu: 'ъ'},
  'Backslash': {code: 'Backslash', key: '\\', keyEnShift: '|'},
  'Delete': {code: 'Delete', key: 'Del', keyCode: 46},
  'CapsLock': {code: 'CapsLock', key: 'CapsLock'},
  'KeyA': {code: 'KeyA', key: 'a', keyRu: 'ф'},
  'KeyS': {code: 'KeyS', key: 's', keyRu: 'ы'},
  'KeyD': {code: 'KeyD', key: 'd', keyRu: 'в'},
  'KeyF': {code: 'KeyF', key: 'f', keyRu: 'а'},
  'KeyG': {code: 'KeyG', key: 'g', keyRu: 'п'},
  'KeyH': {code: 'KeyH', key: 'h', keyRu: 'р'},
  'KeyJ': {code: 'KeyJ', key: 'j', keyRu: 'о'},
  'KeyK': {code: 'KeyK', key: 'k', keyRu: 'л'},
  'KeyL': {code: 'KeyL', key: 'l', keyRu: 'д'},
  'Semicolon': {code: 'Semicolon', key: ';', keyEnShift: ':', keyRu: 'ж'},
  'Quote': {code: 'Quote', key: "'", keyEnShift: '"', keyRu: 'э'},
  'Enter': {code: 'Enter', key: 'Enter'},
  'ShiftLeft': {code: 'ShiftLeft', key: 'Shift'},
  'KeyZ': {code: 'KeyZ', key: 'z', keyRu: 'я'},
  'KeyX': {code: 'KeyX', key: 'x', keyRu: 'ч'},
  'KeyC': {code: 'KeyC', key: 'c', keyRu: 'с'},
  'KeyV': {code: 'KeyV', key: 'v', keyRu: 'м'},
  'KeyB': {code: 'KeyB', key: 'b', keyRu: 'и'},
  'KeyN': {code: 'KeyN', key: 'n', keyRu: 'т'},
  'KeyM': {code: 'KeyM', key: 'm', keyRu: 'ь'},
  'Comma': {code: 'Comma', key: ',', keyEnShift: '<', keyRu: 'б'},
  'Period': {code: 'Period', key: '.', keyEnShift: '>', keyRu: 'ю'},
  'Slash': {code: 'Slash', key: '/', keyEnShift: '?', keyRu: '.', keyRuShift: '.'},
  'ArrowUp': {code: 'ArrowUp', key: '▲', keuRuShift: '.'},
  'ShiftRight': {code: 'ShiftRight', key: 'Shift'},
  'ControlLeft': {code: 'ControlLeft', key: 'Ctrl'},
  'MetaLeft': {code: 'MetaLeft', key: 'Win'},
  'AltLeft': {code: 'AltLeft', key: 'Alt'},
  'Space': {code: 'Space', key: ' '},
  'AltRight': {code: 'AltRight', key: 'Alt'},
  'ArrowLeft': {code: 'ArrowLeft', key: '◄'},
  'ArrowDown': {code: 'ArrowDown', key: '▼'},
  'ArrowRight': {code: 'ArrowRight', key: '►'},
  'ControlRight': {code: 'ControlRight', key: 'Ctrl'}
}

export { keys };